"use client";

import React, { useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import { getApiErrorMessage } from "@/lib/toast-utils";
import { useToast } from "@/providers/toast-provider";
import { Skeleton } from "@/components/ui/skeleton";
import { AlertCircle, ArrowRight, Check, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, ExternalLink, FileCheck2, FileText, GraduationCap, Loader2, Mail, MapPin, Phone, RefreshCw, ShieldCheck, Sprout, UserRound, X, XCircle } from "lucide-react";

interface ExpertDoc { id?: number | string; documentType?: string; title: string; fileName: string; fileType?: string; fileSize?: string; fileUrl?: string; uploadedAt?: string; }
interface CropDetail { id: number; cropName: string; cropEmoji?: string; categoryName?: string; expertiseType?: string; verificationStatus?: string; }
interface PendingExpert {
  profileId: number; fullName: string; email: string; phone?: string; designation?: string; organization?: string;
  yearsOfExperience?: number; qualification?: string; institution?: string; bio?: string; websiteUrl?: string;
  primaryCrops?: string[]; secondaryCrops?: string[]; cropDetails?: CropDetail[]; specializations?: string[];
  locations?: string[]; documents?: ExpertDoc[]; verifiedExpert?: boolean; verificationStatus?: string;
  applicationStatus?: string; adminNotes?: string; submittedAt?: string;
}

interface VerificationStats {
  totalExperts: number;
  verifiedExperts: number;
  pendingVerifications: number;
  suspendedExperts: number;
}

const PAGE_SIZE = 5;
const formatDate = (value?: string) => { if (!value) return "Not provided"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }); };
const statusLabel = (value?: string) => (value || "PENDING").replaceAll("_", " ");
const statusTone = (value?: string) => { const status = value?.toUpperCase(); if (status === "APPROVED" || status === "VERIFIED") return "bg-emerald-50 text-emerald-700 border-emerald-200"; if (status === "REJECTED") return "bg-rose-50 text-rose-700 border-rose-200"; if (status === "UNDER_REVIEW") return "bg-blue-50 text-blue-700 border-blue-200"; if (status === "ADDITIONAL_INFO_REQUIRED") return "bg-orange-50 text-orange-700 border-orange-200"; return "bg-amber-50 text-amber-700 border-amber-200"; };

function StatusBadge({ value }: { value?: string }) { return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.08em] ${statusTone(value)}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{statusLabel(value)}</span>; }
function EmptyState({ children }: { children: React.ReactNode }) { return <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50/60 px-4 py-6 text-center text-sm text-slate-500">{children}</div>; }

export function VerificationQueue() {
  const { toast } = useToast();
  const [experts, setExperts] = useState<PendingExpert[]>([]); const [selected, setSelected] = useState<PendingExpert | null>(null);
  const [stats, setStats] = useState<VerificationStats | null>(null);
  const [isLoading, setIsLoading] = useState(true); const [isRefreshing, setIsRefreshing] = useState(false); const [loadError, setLoadError] = useState<string | null>(null);
  const [processing, setProcessing] = useState(false); const [listPage, setListPage] = useState(0); const [approveNotes, setApproveNotes] = useState("");
  const [reviewNotes, setReviewNotes] = useState(""); const [reviewAction, setReviewAction] = useState<"reject" | "info" | null>(null); const [viewingDoc, setViewingDoc] = useState<ExpertDoc | null>(null);

  const fetchPending = useCallback(async () => { setLoadError(null); try { const [data, dashboardStats] = await Promise.all([api.get<PendingExpert[]>("/v1/admin/experts/pending"), api.get<VerificationStats>("/v1/admin/dashboard/stats")]); const next = Array.isArray(data) ? data : []; setExperts(next); setStats(dashboardStats); setSelected((current) => next.find((item) => item.profileId === current?.profileId) ?? next[0] ?? null); } catch (error) { setLoadError(getApiErrorMessage(error, "Unable to load expert verification details.")); } finally { setIsLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void fetchPending(); }, 0); return () => window.clearTimeout(timer); }, [fetchPending]);
  const removeReviewedExpert = (profileId: number) => setExperts((current) => { const next = current.filter((expert) => expert.profileId !== profileId); setSelected((currentSelected) => currentSelected?.profileId === profileId ? next[0] ?? null : currentSelected); return next; });
  const handleApprove = async () => { if (!selected) return; setProcessing(true); try { await api.post(`/v1/admin/experts/${selected.profileId}/approve`, { notes: approveNotes.trim() || "Approved by platform administrator" }); toast.success({ title: "Expert approved", description: `${selected.fullName} has been approved as a Verified Expert.` }); removeReviewedExpert(selected.profileId); setApproveNotes(""); } catch (error) { toast.error({ title: "Failed to approve", description: getApiErrorMessage(error, "Failed to approve. Please try again.") }); } finally { setProcessing(false); } };
  const submitReviewAction = async () => { if (!selected || !reviewAction || !reviewNotes.trim()) return; setProcessing(true); try { const action = reviewAction === "reject" ? "reject" : "request-info"; await api.post(`/v1/admin/experts/${selected.profileId}/${action}`, { notes: reviewNotes.trim() }); toast.success({ title: reviewAction === "reject" ? "Application rejected" : "Information requested", description: reviewAction === "reject" ? `Feedback sent for ${selected.fullName}.` : `Additional information requested from ${selected.fullName}.` }); removeReviewedExpert(selected.profileId); setReviewAction(null); setReviewNotes(""); } catch (error) { toast.error({ title: "Action failed", description: getApiErrorMessage(error, "The review action could not be completed.") }); } finally { setProcessing(false); } };
  const startReview = async () => { if (!selected) return; setProcessing(true); try { await api.post(`/v1/admin/experts/${selected.profileId}/start-review`); toast.info({ title: "Review started", description: "Application marked as Under Review." }); await fetchPending(); } catch (error) { toast.error({ title: "Failed to start review", description: getApiErrorMessage(error, "The review could not be started.") }); } finally { setProcessing(false); } };

  const totalPages = Math.max(1, Math.ceil(experts.length / PAGE_SIZE)); const visibleExperts = experts.slice(listPage * PAGE_SIZE, (listPage + 1) * PAGE_SIZE);
  const status = selected?.verificationStatus || selected?.applicationStatus || "PENDING"; const isApproved = selected?.verifiedExpert || status === "APPROVED" || status === "VERIFIED"; const isRejected = status === "REJECTED";
  const cropDetails = selected?.cropDetails ?? []; const crops: CropDetail[] = cropDetails.length ? cropDetails : [...(selected?.primaryCrops ?? []).map((crop, index) => ({ id: index, cropName: crop, expertiseType: "PRIMARY" })), ...(selected?.secondaryCrops ?? []).map((crop, index) => ({ id: index + 1000, cropName: crop, expertiseType: "SECONDARY" }))];

  if (isLoading) return <div className="grid grid-cols-1 gap-5 xl:grid-cols-[300px_minmax(0,1fr)]" aria-busy="true" aria-label="Loading verification applications"><div className="space-y-3">{[1, 2, 3, 4].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex gap-3"><Skeleton className="h-10 w-10 rounded-full" /><div className="flex-1 space-y-2"><Skeleton className="h-3 w-3/4" /><Skeleton className="h-3 w-1/2" /></div></div><Skeleton className="mt-4 h-3 w-2/3" /></div>)}</div><div className="rounded-2xl border border-slate-200 bg-white p-6"><Skeleton className="h-7 w-1/3" /><Skeleton className="mt-5 h-28 w-full" /><div className="mt-5 grid grid-cols-2 gap-4"><Skeleton className="h-24" /><Skeleton className="h-24" /></div><Skeleton className="mt-5 h-32 w-full" /></div></div>;
  if (loadError) return <div className="rounded-2xl border border-rose-200 bg-rose-50/60 p-10 text-center"><AlertCircle className="mx-auto h-8 w-8 text-rose-500" /><h2 className="mt-3 text-base font-bold text-slate-900">Unable to load expert verification details.</h2><p className="mt-1 text-sm text-slate-600">{loadError}</p><button onClick={() => { setIsLoading(true); fetchPending(); }} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white"><RefreshCw className="h-4 w-4" /> Try Again</button></div>;

  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatCard label="Pending reviews" value={stats?.pendingVerifications ?? experts.length} tone="amber" hint="Requires your action" /><StatCard label="Total experts" value={stats?.totalExperts ?? 0} tone="blue" hint="All registered experts" /><StatCard label="Verified experts" value={stats?.verifiedExperts ?? 0} tone="green" hint="Currently verified" /><StatCard label="Suspended experts" value={stats?.suspendedExperts ?? 0} tone="rose" hint="Account status" /></div><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Verification workspace</p><p className="mt-1 text-sm text-slate-500">{experts.length} application{experts.length === 1 ? "" : "s"} awaiting review</p></div><button onClick={async () => { setIsRefreshing(true); await fetchPending(); setIsRefreshing(false); }} disabled={isRefreshing} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-sm font-semibold text-slate-700 shadow-sm"><RefreshCw className={`h-4 w-4 ${isRefreshing ? "animate-spin" : ""}`} /> Refresh queue</button></div>
    {experts.length === 0 ? <div className="rounded-2xl border border-slate-200 bg-white py-20 text-center shadow-sm"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-500" /><h2 className="mt-4 text-lg font-bold text-slate-900">Queue is clear</h2><p className="mt-1 text-sm text-slate-500">There are no expert applications awaiting review.</p></div> : <div className="grid grid-cols-1 items-start gap-5 xl:grid-cols-[300px_minmax(0,1fr)]"><aside className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm xl:sticky xl:top-24"><div className="flex items-center justify-between px-2 pb-3"><h2 className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">Applications</h2><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">{experts.length}</span></div><div className="space-y-2">{visibleExperts.map((expert) => <button key={expert.profileId} onClick={() => { setSelected(expert); setApproveNotes(""); setReviewAction(null); }} className={`w-full rounded-xl border p-3 text-left transition ${selected?.profileId === expert.profileId ? "border-emerald-300 bg-emerald-50/60" : "border-slate-100 hover:border-slate-300 hover:bg-slate-50"}`}><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-sm font-bold text-emerald-800">{expert.fullName.charAt(0).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-900">{expert.fullName}</p><p className="mt-0.5 truncate text-xs text-slate-500">{expert.designation || "Expert applicant"}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-slate-400"><Clock3 className="h-3 w-3" /> {formatDate(expert.submittedAt)}</p></div></div><div className="mt-3 flex items-center justify-between gap-2"><StatusBadge value={expert.verificationStatus || expert.applicationStatus} /><ArrowRight className="h-3.5 w-3.5 text-slate-400" /></div></button>)}</div>{totalPages > 1 && <div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-xs text-slate-400">Page {listPage + 1} of {totalPages}</span><div className="flex gap-1"><button aria-label="Previous page" onClick={() => setListPage((page) => Math.max(0, page - 1))} disabled={listPage === 0} className="rounded-lg border border-slate-200 p-1.5 disabled:opacity-40"><ChevronLeft className="h-3.5 w-3.5" /></button><button aria-label="Next page" onClick={() => setListPage((page) => Math.min(totalPages - 1, page + 1))} disabled={listPage === totalPages - 1} className="rounded-lg border border-slate-200 p-1.5 disabled:opacity-40"><ChevronRight className="h-3.5 w-3.5" /></button></div></div>}</aside>
      {selected && <main className="min-w-0 space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-emerald-700 text-2xl font-bold text-white">{selected.fullName.charAt(0).toUpperCase()}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-xl font-bold text-slate-950">{selected.fullName}</h2><StatusBadge value={status} /></div><p className="mt-1 text-sm text-slate-500">{selected.designation || "Expert applicant"}{selected.organization ? ` at ${selected.organization}` : ""}</p><p className="mt-2 text-xs text-slate-400">Application #{selected.profileId} · Submitted {formatDate(selected.submittedAt)}</p></div></div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 font-semibold text-slate-600">Account: <strong className="text-emerald-700">ACTIVE</strong></span><span className={`rounded-lg border px-3 py-2 font-semibold ${statusTone(status)}`}>Verification: <strong>{statusLabel(status)}</strong></span></div></div><div className="mt-6 grid grid-cols-1 gap-3 border-t border-slate-100 pt-5 sm:grid-cols-3"><InfoItem icon={<Mail />} label="Email" value={selected.email} /><InfoItem icon={<Phone />} label="Phone" value={selected.phone} /><InfoItem icon={<MapPin />} label="Location" value={selected.locations?.join(", ")} /></div></section>
        <div className="grid grid-cols-1 items-start gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="min-w-0 space-y-5"><ReviewSection icon={<UserRound />} title="Professional information"><div className="grid grid-cols-1 gap-x-6 gap-y-5 sm:grid-cols-2"><Field label="Professional title" value={selected.designation} /><Field label="Organization / institution" value={selected.organization || selected.institution} /><Field label="Qualification" value={selected.qualification} /><Field label="Years of experience" value={selected.yearsOfExperience != null ? `${selected.yearsOfExperience} years` : undefined} /></div><div className="mt-5 border-t border-slate-100 pt-4"><Field label="Professional bio" value={selected.bio} multiline /></div></ReviewSection>
          <ReviewSection icon={<Sprout />} title="Submitted expertise" count={crops.length}>{(selected.specializations ?? []).length > 0 && <div className="mb-4 flex flex-wrap gap-2">{selected.specializations?.map((item) => <span key={item} className="rounded-lg border border-blue-200 bg-blue-50 px-2.5 py-1.5 text-xs font-semibold text-blue-700">{item}</span>)}</div>}{crops.length === 0 ? <EmptyState>No expertise submitted.</EmptyState> : <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{crops.map((crop, index) => <div key={`${crop.id}-${index}`} className="rounded-xl border border-slate-200 p-3.5"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{crop.cropEmoji ? `${crop.cropEmoji} ` : ""}{crop.cropName}</p><p className="mt-1 text-xs text-slate-500">{crop.categoryName || "Crop expertise"}</p></div><span className="rounded-md bg-emerald-50 px-2 py-1 text-[10px] font-bold uppercase text-emerald-700">{crop.expertiseType || "SUBMITTED"}</span></div>{crop.verificationStatus && <p className="mt-3 flex items-center gap-1.5 text-xs text-slate-500"><ShieldCheck className="h-3.5 w-3.5" /> {statusLabel(crop.verificationStatus)}</p>}</div>)}</div>}</ReviewSection>
          <ReviewSection icon={<GraduationCap />} title="Qualifications & experience"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field label="Education" value={selected.qualification || selected.institution} /><Field label="Previous organization" value={selected.organization} /><Field label="Specialization" value={selected.specializations?.join(", ")} /><Field label="Service locations" value={selected.locations?.join(", ")} /></div></ReviewSection>
          <ReviewSection icon={<FileCheck2 />} title="Documents & credentials" count={selected.documents?.length ?? 0}>{!selected.documents?.length ? <EmptyState>No documents uploaded.</EmptyState> : <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{selected.documents.map((doc, index) => <div key={doc.id || index} className="rounded-xl border border-slate-200 p-3.5"><div className="flex gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-600"><FileText className="h-4 w-4" /></div><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{doc.title || doc.fileName}</p><p className="mt-0.5 truncate text-xs text-slate-500">{doc.documentType || "Submitted document"}</p><p className="mt-1 text-[11px] text-slate-400">{doc.fileName} · {doc.fileSize || "Size not provided"}</p></div></div><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-[11px] text-slate-400">Uploaded {formatDate(doc.uploadedAt)}</span><button onClick={() => setViewingDoc(doc)} disabled={!doc.fileUrl} className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700 disabled:cursor-not-allowed disabled:text-slate-400"><ExternalLink className="h-3.5 w-3.5" /> {doc.fileUrl ? "Open" : "Preview unavailable"}</button></div></div>)}</div>}</ReviewSection></div>
          <aside className="space-y-5 lg:sticky lg:top-24"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-700" /><h2 className="text-sm font-bold text-slate-900">Admin decision</h2></div><p className="mt-2 text-xs leading-relaxed text-slate-500">Review the submitted credentials before changing this expert&apos;s verification status.</p>{isApproved ? <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><CheckCircle2 className="h-5 w-5 text-emerald-600" /><p className="mt-2 text-sm font-bold text-emerald-800">Verified</p></div> : isRejected ? <div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4"><XCircle className="h-5 w-5 text-rose-600" /><p className="mt-2 text-sm font-bold text-rose-800">Rejected</p><p className="mt-1 text-xs text-rose-700">{selected.adminNotes || "The application was rejected."}</p></div> : <><label className="mt-5 block text-xs font-bold text-slate-700" htmlFor="approve-notes">Review notes <span className="font-normal text-slate-400">(optional)</span></label><textarea id="approve-notes" value={approveNotes} onChange={(event) => setApproveNotes(event.target.value)} rows={3} maxLength={500} placeholder="Add context for this decision..." className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100" /><div className="mt-3 space-y-2"><button onClick={handleApprove} disabled={processing} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50">{processing ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />} Approve expertise</button>{status !== "UNDER_REVIEW" && <button onClick={startReview} disabled={processing} className="flex w-full items-center justify-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-2.5 text-sm font-bold text-blue-700 disabled:opacity-50"><Clock3 className="h-4 w-4" /> Start review</button>}<div className="grid grid-cols-2 gap-2"><button onClick={() => setReviewAction("reject")} disabled={processing} className="rounded-xl border border-rose-200 px-3 py-2.5 text-sm font-bold text-rose-700">Reject</button><button onClick={() => setReviewAction("info")} disabled={processing} className="rounded-xl border border-orange-200 px-3 py-2.5 text-sm font-bold text-orange-700">Request info</button></div></div></>}</section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-bold text-slate-900">Review history</h2><div className="mt-4 space-y-4"><TimelineItem label="Application submitted" value={formatDate(selected.submittedAt)} /><TimelineItem label={statusLabel(status)} value="Current status" /></div></section></aside></div></main>}
    </div>}
    {reviewAction && selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true" aria-labelledby="review-action-title"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><h2 id="review-action-title" className="text-base font-bold text-slate-900">{reviewAction === "reject" ? "Reject application" : "Request additional information"}</h2><p className="mt-1 text-sm text-slate-500">{selected.fullName}</p></div><button aria-label="Close dialog" onClick={() => setReviewAction(null)}><X className="h-4 w-4 text-slate-400" /></button></div><label htmlFor="review-notes" className="mt-5 block text-xs font-bold text-slate-700">{reviewAction === "reject" ? "Rejection reason" : "Information required"} <span className="text-rose-500">*</span></label><textarea id="review-notes" autoFocus value={reviewNotes} onChange={(event) => setReviewNotes(event.target.value)} rows={5} maxLength={1000} className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm outline-none focus:border-emerald-400" /><div className="mt-4 flex flex-col-reverse gap-2 sm:flex-row"><button onClick={() => setReviewAction(null)} className="flex-1 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancel</button><button onClick={submitReviewAction} disabled={!reviewNotes.trim() || processing} className={`flex-1 rounded-xl px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50 ${reviewAction === "reject" ? "bg-rose-700" : "bg-orange-600"}`}>{processing ? <Loader2 className="mx-auto h-4 w-4 animate-spin" /> : reviewAction === "reject" ? "Confirm rejection" : "Request information"}</button></div></div></div>}
    {viewingDoc && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" role="dialog" aria-modal="true" aria-labelledby="document-title"><div className="flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 id="document-title" className="text-base font-bold text-slate-900">{viewingDoc.title || viewingDoc.fileName}</h2><p className="mt-0.5 text-xs text-slate-500">{viewingDoc.fileName}</p></div><button aria-label="Close document preview" onClick={() => setViewingDoc(null)}><X className="h-4 w-4 text-slate-400" /></button></div><div className="min-h-[260px] flex-1 overflow-auto bg-slate-100 p-5">{viewingDoc.fileUrl?.startsWith("data:image") ? <img src={viewingDoc.fileUrl} alt={viewingDoc.title} className="mx-auto max-h-[65vh] object-contain" /> : viewingDoc.fileUrl?.startsWith("data:application/pdf") ? <iframe src={viewingDoc.fileUrl} title={viewingDoc.title} className="h-[65vh] w-full rounded-lg border bg-white" /> : <div className="flex h-60 flex-col items-center justify-center gap-3 rounded-xl border border-dashed border-slate-300 bg-white text-center"><FileText className="h-9 w-9 text-slate-400" /><p className="text-sm text-slate-600">This document is available through its secure file link.</p><a href={viewingDoc.fileUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Download className="h-3.5 w-3.5" /> Open document</a></div>}</div></div></div>}
  </div>;
}

function InfoItem({ icon, label, value }: { icon: React.ReactNode; label: string; value?: string }) { return <div className="flex min-w-0 items-start gap-2.5"><span className="mt-0.5 text-slate-400 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">{label}</p><p className="mt-1 truncate text-sm font-medium text-slate-700">{value || "Not provided"}</p></div></div>; }
function StatCard({ label, value, hint, tone }: { label: string; value: number; hint: string; tone: "amber" | "blue" | "green" | "rose" }) { const toneClasses = { amber: "bg-amber-50 text-amber-600", blue: "bg-blue-50 text-blue-600", green: "bg-emerald-50 text-emerald-600", rose: "bg-rose-50 text-rose-600" }; return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-[10px] text-slate-400">{hint}</p></div><span className={`h-9 w-9 rounded-full ${toneClasses[tone]}`} /></div></div>; }
function Field({ label, value, multiline = false }: { label: string; value?: string; multiline?: boolean }) { return <div><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">{label}</p><p className={`mt-1 text-sm ${value ? "text-slate-700" : "text-slate-400"} ${multiline ? "leading-relaxed" : "font-medium"}`}>{value || "Not provided"}</p></div>; }
function ReviewSection({ icon, title, count, children }: { icon: React.ReactNode; title: string; count?: number; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-sm font-bold text-slate-900"><span className="text-emerald-700 [&>svg]:h-4 [&>svg]:w-4">{icon}</span>{title}</h2>{count !== undefined && <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold text-slate-600">{count}</span>}</div>{children}</section>; }
function TimelineItem({ label, value }: { label: string; value: string }) { return <div className="flex gap-3"><div className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-emerald-300 bg-emerald-50 text-emerald-600"><span className="h-1.5 w-1.5 rounded-full bg-current" /></div><div><p className="text-xs font-semibold text-slate-700">{label}</p><p className="mt-0.5 text-[11px] text-slate-400">{value}</p></div></div>; }
export function VerificationCard(_props: { name: string; credential: string }) { void _props; return <VerificationQueue />; }